
function add(a,b){return a + b}
function subtract(a,b){return a - b}
function multiply(a,b){return a * b}
function divide(a,b){return a / b}
var addButton = document.getElementById("addbutton")
var subtractButton = document.getElementById("subtractbutton")
var multiplyButton = document.getElementById("multiplybutton")
var divideButton = document.getElementById("dividebutton")
var nineButton = document.getElementById("ninebutton")
var eightButton = document.getElementById("eightbutton")
var sevenButton = document.getElementById("sevenbutton")
var sixButton = document.getElementById("sixbutton")
var fiveButton = document.getElementById("fivebutton")
var fourButton = document.getElementById("fourbutton")
var threeButton = document.getElementById("threebutton")
var twoButton = document.getElementById("twobutton")
var oneButton = document.getElementById("onebutton")
var zeroButton = document.getElementById("zerobutton")
addButton.addEventListener("click", add())
subtractButton.subtractEventListener("click", subtract())
multiplyButton.multiplyEventListener("click", multiply())
divideButton.divideEventListener("click", divide())
nineButton.subtractEventListener("click", function(){display.innerHTML += 9})
subtractButton.subtractEventListener("click", subtract())
nineButton.subtractEventListener("click", function(){display.innerHTML += 8})
subtractButton.subtractEventListener("click", subtract())
nineButton.subtractEventListener("click", function(){display.innerHTML += 7})
subtractButton.subtractEventListener("click", subtract())
nineButton.subtractEventListener("click", function(){display.innerHTML += 6})
subtractButton.subtractEventListener("click", subtract())
nineButton.subtractEventListener("click", function(){display.innerHTML += 5})
subtractButton.subtractEventListener("click", subtract())
nineButton.subtractEventListener("click", function(){display.innerHTML += 4})
subtractButton.subtractEventListener("click", subtract())
nineButton.subtractEventListener("click", function(){display.innerHTML += 3})
subtractButton.subtractEventListener("click", subtract())
nineButton.subtractEventListener("click", function(){display.innerHTML += 2})
subtractButton.subtractEventListener("click", subtract())
nineButton.subtractEventListener("click", function(){display.innerHTML += 1})
subtractButton.subtractEventListener("click", subtract())
nineButton.subtractEventListener("click", function(){display.innerHTML += 0})
